name: Scope Node.js TypeORM Starter

on: [push]

jobs:
  scope:
    env:
      DB_USER: userdemonodejs
      DB_HOST: localhost
      DB_NAME: demonodejs
      DB_PASS: password
      DB_PORT: 5432
    services:
      postgres:
        image: postgres:11.5
        env:
          POSTGRES_USER: userdemonodejs
          POSTGRES_PASSWORD: password
          POSTGRES_DB: demonodejs
        ports:
          - 5432:5432
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
      - name: Install dependencies
        run: npm install
      - name: Scope for Javascript
        uses: undefinedlabs/scope-for-javascript-action@v1
        with:
          dsn: ${{secrets.SCOPE_DSN}}
          jest-command: npm test
